/* The following code was generated by JFlex 1.6.1 */

package proyecto;
import static proyecto.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/Ricardo/Documents/GitHub/BatLan/jflex/src/proyecto/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\7\1\7\1\72\1\72\1\7\22\0\1\7\1\63\1\67"+
    "\2\0\1\45\1\62\1\70\1\52\1\4\1\60\1\57\1\51\1\61"+
    "\1\50\1\64\12\2\1\56\1\71\1\47\1\55\1\46\1\0\1\44"+
    "\1\1\1\37\2\1\1\1\1\34\2\1\1\33\1\1\2\1\1\40"+
    "\1\1\1\1\1\32\1\1\1\1\1\35\1\1\1\1\1\1\1\41"+
    "\3\1\1\30\1\0\1\31\1\65\1\1\1\0\1\22\1\10\1\26"+
    "\1\14\1\20\1\21\1\25\1\27\1\11\2\1\1\17\1\42\1\12"+
    "\1\15\1\36\1\1\1\24\1\23\1\13\1\16\1\43\1\5\1\3"+
    "\1\6\1\1\1\53\1\66\1\54\7\0\1\72\u1fa2\0\1\72\1\72"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\2\2\1\3\1\2\1\4\17\2\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\2\1\25"+
    "\1\2\1\26\1\27\2\30\1\0\1\30\1\31\1\32"+
    "\7\30\1\33\21\30\1\0\1\34\1\35\1\36\1\0"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\0"+
    "\1\46\2\0\1\47\25\30\1\50\1\33\16\30\1\0"+
    "\10\30\1\33\6\30\1\51\7\30";

  private static int [] zzUnpackAction() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\73\0\261\0\354\0\u0127\0\u0162"+
    "\0\u019d\0\u01d8\0\u0213\0\u024e\0\u0289\0\u02c4\0\u02ff\0\u033a"+
    "\0\u0375\0\u03b0\0\u03eb\0\u0426\0\u0461\0\73\0\73\0\73"+
    "\0\u049c\0\73\0\73\0\73\0\73\0\73\0\u04d7\0\73"+
    "\0\u0512\0\u054d\0\u0588\0\u05c3\0\u05fe\0\u0639\0\73\0\u0674"+
    "\0\u06af\0\73\0\u06ea\0\u0725\0\u0760\0\u079b\0\354\0\u07d6"+
    "\0\u0811\0\u084c\0\u0887\0\u08c2\0\u08fd\0\u0938\0\u0973\0\u06ea"+
    "\0\u09ae\0\u09e9\0\u0a24\0\u0a5f\0\u0a9a\0\u0ad5\0\u0b10\0\u0b4b"+
    "\0\u0b86\0\u0bc1\0\u0bfc\0\u0c37\0\u0c72\0\u0cad\0\u0ce8\0\u0d23"+
    "\0\u0d5e\0\u049c\0\73\0\73\0\73\0\u0d99\0\73\0\73"+
    "\0\73\0\73\0\73\0\73\0\73\0\u06af\0\73\0\u0dd4"+
    "\0\u0e0f\0\u0760\0\u0e4a\0\u0e85\0\u0ec0\0\u0efb\0\u0f36\0\u0f71"+
    "\0\u0fac\0\u0fe7\0\u1022\0\u105d\0\u1098\0\u10d3\0\u110e\0\u1149"+
    "\0\u1184\0\u11bf\0\u11fa\0\u1235\0\u1270\0\u12ab\0\u12e6\0\73"+
    "\0\u1321\0\u135c\0\u1397\0\u13d2\0\u140d\0\u1448\0\u1483\0\u14be"+
    "\0\u14f9\0\u1534\0\u156f\0\u15aa\0\u15e5\0\u1620\0\u165b\0\u1696"+
    "\0\u16d1\0\u170c\0\u1747\0\u1782\0\u17bd\0\u17f8\0\u1833\0\u186e"+
    "\0\73\0\u18a9\0\u18e4\0\u191f\0\u195a\0\u1995\0\u19d0\0\u06ea"+
    "\0\u1a0b\0\u1a46\0\u1a81\0\u1abc\0\u1af7\0\u1b32\0\u1b6d";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\1\3\1\4\1\5\1\3\1\6"+
    "\1\7\1\10\1\3\1\11\1\12\3\3\1\13\1\14"+
    "\1\3\1\15\2\3\1\16\1\17\2\2\1\20\1\3"+
    "\1\21\1\22\1\23\1\3\1\24\1\3\1\25\1\3"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\2\75\0\1\53"+
    "\1\54\1\53\1\0\2\53\1\0\20\53\2\0\12\53"+
    "\4\0\1\55\5\0\1\55\15\0\1\53\1\54\1\53"+
    "\1\0\2\53\1\0\17\53\1\56\2\0\12\53\4\0"+
    "\1\55\5\0\1\55\16\0\1\57\45\0\1\60\23\0"+
    "\1\53\1\54\1\53\1\0\2\53\1\0\1\61\1\62"+
    "\2\53\1\63\2\53\1\64\1\53\1\65\1\53\1\66"+
    "\2\53\1\67\1\53\2\0\12\53\4\0\1\55\5\0"+
    "\1\55\15\0\1\53\1\54\1\53\1\0\2\53\1\0"+
    "\11\53\1\70\6\53\2\0\10\53\1\71\1\53\4\0"+
    "\1\55\5\0\1\55\15\0\1\53\1\54\1\53\1\0"+
    "\2\53\1\0\14\53\1\72\2\53\1\73\2\0\12\53"+
    "\4\0\1\55\5\0\1\55\15\0\1\53\1\54\1\53"+
    "\1\0\2\53\1\0\5\53\1\70\2\53\1\74\7\53"+
    "\2\0\12\53\4\0\1\55\5\0\1\55\15\0\1\53"+
    "\1\54\1\75\1\0\2\53\1\0\6\53\1\76\1\77"+
    "\10\53\2\0\12\53\4\0\1\55\5\0\1\55\15\0"+
    "\1\53\1\54\1\53\1\0\2\53\1\0\5\53\1\100"+
    "\4\53\1\101\5\53\2\0\12\53\4\0\1\55\5\0"+
    "\1\55\15\0\1\53\1\54\1\53\1\0\2\53\1\0"+
    "\1\53\1\102\16\53\2\0\12\53\4\0\1\55\5\0"+
    "\1\55\15\0\1\53\1\54\1\53\1\0\2\53\1\0"+
    "\12\53\1\77\5\53\2\0\12\53\4\0\1\55\5\0"+
    "\1\55\15\0\1\53\1\54\1\53\1\0\2\53\1\0"+
    "\10\53\1\103\7\53\2\0\12\53\4\0\1\55\5\0"+
    "\1\55\15\0\1\53\1\54\1\53\1\0\2\53\1\0"+
    "\20\53\2\0\1\53\1\70\10\53\4\0\1\55\5\0"+
    "\1\55\15\0\1\53\1\54\1\53\1\0\2\53\1\0"+
    "\1\53\1\70\16\53\2\0\12\53\4\0\1\55\5\0"+
    "\1\55\15\0\1\53\1\54\1\53\1\0\1\104\1\53"+
    "\1\0\3\53\1\105\14\53\2\0\12\53\4\0\1\55"+
    "\5\0\1\55\15\0\1\53\1\54\1\53\1\0\2\53"+
    "\1\0\6\53\1\106\5\53\1\107\3\53\2\0\12\53"+
    "\4\0\1\55\5\0\1\55\15\0\1\53\1\54\1\53"+
    "\1\0\2\53\1\0\13\53\1\110\4\53\2\0\12\53"+
    "\4\0\1\55\5\0\1\55\15\0\1\53\1\54\1\53"+
    "\1\0\2\53\1\0\12\53\1\111\5\53\2\0\12\53"+
    "\4\0\1\55\5\0\1\55\15\0\3\112\1\0\23\112"+
    "\2\0\12\112\2\0\1\113\101\0\1\114\72\0\1\115"+
    "\16\0\3\116\1\0\23\116\2\0\12\116\11\0\1\117"+
    "\2\0\1\120\14\0\1\57\45\0\1\60\4\0\1\121"+
    "\77\0\1\122\65\0\1\123\72\0\1\124\103\0\1\125"+
    "\5\0\3\126\1\0\23\126\2\0\12\126\2\0\4\126"+
    "\3\0\2\126\1\0\1\126\3\0\1\126\2\0\1\127"+
    "\1\0\1\126\2\0\1\53\1\54\1\53\1\0\2\53"+
    "\1\130\20\53\2\0\12\53\4\0\1\55\1\0\1\131"+
    "\3\0\1\55\15\0\3\54\1\0\2\54\1\130\20\54"+
    "\2\0\12\54\6\0\1\131\21\0\1\132\1\0\1\132"+
    "\1\0\2\132\1\0\20\132\2\0\12\132\30\0\1\53"+
    "\1\54\1\53\1\0\2\53\1\130\1\53\1\133\16\53"+
    "\2\0\12\53\4\0\1\55\1\0\1\131\3\0\1\55"+
    "\16\0\1\60\71\0\1\53\1\54\1\53\1\0\1\53"+
    "\1\134\1\130\20\53\2\0\12\53\4\0\1\55\1\0"+
    "\1\131\3\0\1\55\15\0\1\53\1\54\1\53\1\0"+
    "\2\53\1\130\2\53\1\135\15\53\2\0\12\53\4\0"+
    "\1\55\1\0\1\131\3\0\1\55\15\0\1\53\1\54"+
    "\1\53\1\0\2\53\1\130\5\53\1\136\12\53\2\0"+
    "\12\53\4\0\1\55\1\0\1\131\3\0\1\55\15\0"+
    "\1\53\1\54\1\53\1\0\2\53\1\130\5\53\1\137"+
    "\12\53\2\0\12\53\4\0\1\55\1\0\1\131\3\0"+
    "\1\55\15\0\1\53\1\54\1\53\1\0\2\53\1\130"+
    "\7\53\1\140\10\53\2\0\12\53\4\0\1\55\1\0"+
    "\1\131\3\0\1\55\15\0\1\53\1\54\1\53\1\0"+
    "\2\53\1\130\3\53\1\141\13\53\1\142\2\0\12\53"+
    "\4\0\1\55\1\0\1\131\3\0\1\55\15\0\1\53"+
    "\1\54\1\53\1\0\2\53\1\130\17\53\1\143\2\0"+
    "\12\53\4\0\1\55\1\0\1\131\3\0\1\55\15\0"+
    "\1\53\1\54\1\53\1\0\2\53\1\130\20\53\2\0"+
    "\4\53\1\142\5\53\4\0\1\55\1\0\1\131\3\0"+
    "\1\55\15\0\1\53\1\54\1\53\1\0\1\53\1\70"+
    "\1\130\6\53\1\144\11\53\2\0\12\53\4\0\1\55"+
    "\1\0\1\131\3\0\1\55\15\0\1\53\1\54\1\53"+
    "\1\0\2\53\1\130\10\53\1\145\3\53\1\146\3\53"+
    "\2\0\12\53\4\0\1\55\1\0\1\131\3\0\1\55"+
    "\15\0\1\53\1\54\1\53\1\0\2\53\1\130\11\53"+
    "\1\147\6\53\2\0\12\53\4\0\1\55\1\0\1\131"+
    "\3\0\1\55\15\0\1\53\1\54\1\53\1\0\2\53"+
    "\1\130\16\53\1\150\1\53\2\0\12\53\4\0\1\55"+
    "\1\0\1\131\3\0\1\55\15\0\1\53\1\54\1\53"+
    "\1\0\2\53\1\130\7\53\1\151\10\53\2\0\12\53"+
    "\4\0\1\55\1\0\1\131\3\0\1\55\15\0\1\53"+
    "\1\54\1\53\1\0\2\53\1\130\13\53\1\144\4\53"+
    "\2\0\12\53\4\0\1\55\1\0\1\131\3\0\1\55"+
    "\15\0\1\53\1\54\1\53\1\0\2\53\1\130\14\53"+
    "\1\70\3\53\2\0\12\53\4\0\1\55\1\0\1\131"+
    "\3\0\1\55\15\0\1\53\1\54\1\53\1\0\2\53"+
    "\1\130\7\53\1\77\10\53\2\0\12\53\4\0\1\55"+
    "\1\0\1\131\3\0\1\55\15\0\1\53\1\54\1\53"+
    "\1\0\2\53\1\130\3\53\1\152\14\53\2\0\12\53"+
    "\4\0\1\55\1\0\1\131\3\0\1\55\15\0\1\53"+
    "\1\54\1\53\1\0\2\53\1\130\14\53\1\144\3\53"+
    "\2\0\12\53\4\0\1\55\1\0\1\131\3\0\1\55"+
    "\15\0\1\53\1\54\1\53\1\0\2\53\1\130\1\53"+
    "\1\153\16\53\2\0\12\53\4\0\1\55\1\0\1\131"+
    "\3\0\1\55\15\0\1\53\1\54\1\53\1\0\2\53"+
    "\1\130\10\53\1\154\7\53\2\0\12\53\4\0\1\55"+
    "\1\0\1\131\3\0\1\55\15\0\1\53\1\54\1\53"+
    "\1\0\2\53\1\130\1\155\17\53\2\0\12\53\4\0"+
    "\1\55\1\0\1\131\3\0\1\55\15\0\1\53\1\54"+
    "\1\53\1\0\2\53\1\130\1\53\1\156\16\53\2\0"+
    "\12\53\4\0\1\55\1\0\1\131\3\0\1\55\15\0"+
    "\1\53\1\54\1\53\1\0\2\53\1\130\15\53\1\157"+
    "\2\53\2\0\12\53\4\0\1\55\1\0\1\131\3\0"+
    "\1\55\15\0\1\53\1\54\1\53\1\0\2\53\1\130"+
    "\1\53\1\145\16\53\2\0\12\53\4\0\1\55\1\0"+
    "\1\131\3\0\1\55\15\0\3\116\1\0\23\116\2\0"+
    "\12\116\14\0\1\120\21\0\1\130\42\0\1\131\22\0"+
    "\1\131\1\0\1\160\67\0\1\53\1\54\1\53\1\0"+
    "\2\53\1\130\7\53\1\144\10\53\2\0\12\53\4\0"+
    "\1\55\1\0\1\131\3\0\1\55\15\0\1\53\1\54"+
    "\1\53\1\0\2\53\1\130\3\53\1\144\14\53\2\0"+
    "\12\53\4\0\1\55\1\0\1\131\3\0\1\55\15\0"+
    "\1\53\1\54\1\53\1\0\2\53\1\130\3\53\1\161"+
    "\14\53\2\0\12\53\4\0\1\55\1\0\1\131\3\0"+
    "\1\55\15\0\1\53\1\54\1\53\1\0\2\53\1\130"+
    "\6\53\1\162\11\53\2\0\12\53\4\0\1\55\1\0"+
    "\1\131\3\0\1\55\15\0\1\53\1\54\1\53\1\0"+
    "\2\53\1\130\2\53\1\163\15\53\2\0\12\53\4\0"+
    "\1\55\1\0\1\131\3\0\1\55\15\0\1\53\1\54"+
    "\1\53\1\0\2\53\1\130\5\53\1\164\12\53\2\0"+
    "\12\53\4\0\1\55\1\0\1\131\3\0\1\55\15\0"+
    "\1\53\1\54\1\53\1\0\2\53\1\130\14\53\1\165"+
    "\3\53\2\0\12\53\4\0\1\55\1\0\1\131\3\0"+
    "\1\55\15\0\1\53\1\54\1\53\1\0\2\53\1\130"+
    "\5\53\1\166\12\53\2\0\12\53\4\0\1\55\1\0"+
    "\1\131\3\0\1\55\15\0\1\53\1\54\1\53\1\0"+
    "\2\53\1\130\12\53\1\100\5\53\2\0\12\53\4\0"+
    "\1\55\1\0\1\131\3\0\1\55\15\0\1\53\1\54"+
    "\1\53\1\0\2\53\1\130\10\53\1\70\7\53\2\0"+
    "\12\53\4\0\1\55\1\0\1\131\3\0\1\55\15\0"+
    "\1\53\1\54\1\53\1\0\2\53\1\130\2\53\1\70"+
    "\15\53\2\0\12\53\4\0\1\55\1\0\1\131\3\0"+
    "\1\55\15\0\1\53\1\54\1\53\1\0\2\53\1\130"+
    "\10\53\1\167\7\53\2\0\12\53\4\0\1\55\1\0"+
    "\1\131\3\0\1\55\15\0\1\53\1\54\1\53\1\0"+
    "\2\53\1\130\10\53\1\170\7\53\2\0\12\53\4\0"+
    "\1\55\1\0\1\131\3\0\1\55\15\0\1\53\1\54"+
    "\1\53\1\0\2\53\1\130\10\53\1\171\7\53\2\0"+
    "\12\53\4\0\1\55\1\0\1\131\3\0\1\55\15\0"+
    "\1\53\1\54\1\53\1\0\2\53\1\130\10\53\1\100"+
    "\7\53\2\0\12\53\4\0\1\55\1\0\1\131\3\0"+
    "\1\55\15\0\1\53\1\54\1\53\1\0\2\53\1\130"+
    "\6\53\1\172\11\53\2\0\12\53\4\0\1\55\1\0"+
    "\1\131\3\0\1\55\15\0\1\53\1\54\1\53\1\0"+
    "\2\53\1\130\3\53\1\173\14\53\2\0\12\53\4\0"+
    "\1\55\1\0\1\131\3\0\1\55\15\0\1\53\1\54"+
    "\1\53\1\0\2\53\1\130\20\53\2\0\4\53\1\174"+
    "\5\53\4\0\1\55\1\0\1\131\3\0\1\55\15\0"+
    "\1\53\1\54\1\53\1\0\2\53\1\130\7\53\1\175"+
    "\10\53\2\0\12\53\4\0\1\55\1\0\1\131\3\0"+
    "\1\55\15\0\1\53\1\54\1\53\1\0\2\53\1\130"+
    "\20\53\2\0\11\53\1\176\4\0\1\55\1\0\1\131"+
    "\3\0\1\55\15\0\1\53\1\54\1\53\1\0\2\53"+
    "\1\130\20\53\2\0\7\53\1\177\2\53\4\0\1\55"+
    "\1\0\1\131\3\0\1\55\15\0\1\53\1\54\1\53"+
    "\1\0\2\53\1\130\20\53\1\200\1\0\12\53\4\0"+
    "\1\55\1\0\1\131\3\0\1\55\15\0\1\53\1\54"+
    "\1\53\1\0\2\53\1\130\1\133\17\53\2\0\12\53"+
    "\4\0\1\55\1\0\1\131\3\0\1\55\15\0\1\53"+
    "\1\54\1\53\1\0\2\53\1\130\15\53\1\70\2\53"+
    "\2\0\12\53\4\0\1\55\1\0\1\131\3\0\1\55"+
    "\15\0\1\53\1\54\1\53\1\0\2\53\1\130\12\53"+
    "\1\201\5\53\2\0\12\53\4\0\1\55\1\0\1\131"+
    "\3\0\1\55\15\0\1\53\1\54\1\53\1\0\2\53"+
    "\1\130\1\53\1\137\16\53\2\0\12\53\4\0\1\55"+
    "\1\0\1\131\3\0\1\55\15\0\1\53\1\54\1\53"+
    "\1\0\2\53\1\130\14\53\1\201\3\53\2\0\12\53"+
    "\4\0\1\55\1\0\1\131\3\0\1\55\15\0\1\53"+
    "\1\54\1\53\1\0\2\53\1\130\12\53\1\202\5\53"+
    "\2\0\12\53\4\0\1\55\1\0\1\131\3\0\1\55"+
    "\15\0\1\53\1\54\1\53\1\0\2\53\1\130\2\53"+
    "\1\203\15\53\2\0\12\53\4\0\1\55\1\0\1\131"+
    "\3\0\1\55\15\0\1\53\1\54\1\53\1\0\2\53"+
    "\1\130\20\53\2\0\4\53\1\201\5\53\4\0\1\55"+
    "\1\0\1\131\3\0\1\55\15\0\1\53\1\54\1\53"+
    "\1\0\2\53\1\130\12\53\1\204\5\53\2\0\12\53"+
    "\4\0\1\55\1\0\1\131\3\0\1\55\15\0\1\53"+
    "\1\54\1\53\1\0\2\53\1\130\16\53\1\205\1\53"+
    "\2\0\12\53\4\0\1\55\1\0\1\131\3\0\1\55"+
    "\15\0\1\53\1\54\1\53\1\0\2\53\1\130\20\53"+
    "\2\0\5\53\1\206\4\53\4\0\1\55\1\0\1\131"+
    "\3\0\1\55\15\0\1\53\1\54\1\53\1\0\2\53"+
    "\1\130\1\53\1\207\16\53\2\0\12\53\4\0\1\55"+
    "\1\0\1\131\3\0\1\55\15\0\1\53\1\54\1\53"+
    "\1\0\2\53\1\130\12\53\1\134\5\53\2\0\12\53"+
    "\4\0\1\55\1\0\1\131\3\0\1\55\15\0\1\53"+
    "\1\54\1\53\1\0\2\53\1\130\12\53\1\210\5\53"+
    "\2\0\12\53\4\0\1\55\1\0\1\131\3\0\1\55"+
    "\45\0\1\211\42\0\1\53\1\54\1\53\1\0\2\53"+
    "\1\130\3\53\1\70\14\53\2\0\12\53\4\0\1\55"+
    "\1\0\1\131\3\0\1\55\15\0\1\53\1\54\1\53"+
    "\1\0\2\53\1\130\4\53\1\212\13\53\2\0\12\53"+
    "\4\0\1\55\1\0\1\131\3\0\1\55\15\0\1\53"+
    "\1\54\1\53\1\0\2\53\1\130\13\53\1\213\4\53"+
    "\2\0\12\53\4\0\1\55\1\0\1\131\3\0\1\55"+
    "\15\0\1\53\1\54\1\53\1\0\2\53\1\130\3\53"+
    "\1\214\14\53\2\0\12\53\4\0\1\55\1\0\1\131"+
    "\3\0\1\55\15\0\1\53\1\54\1\53\1\0\2\53"+
    "\1\130\17\53\1\70\2\0\12\53\4\0\1\55\1\0"+
    "\1\131\3\0\1\55\15\0\1\53\1\54\1\53\1\0"+
    "\1\53\1\215\1\130\20\53\2\0\12\53\4\0\1\55"+
    "\1\0\1\131\3\0\1\55\15\0\1\53\1\54\1\53"+
    "\1\0\2\53\1\130\16\53\1\70\1\53\2\0\12\53"+
    "\4\0\1\55\1\0\1\131\3\0\1\55\15\0\1\53"+
    "\1\54\1\53\1\0\2\53\1\130\14\53\1\216\3\53"+
    "\2\0\12\53\4\0\1\55\1\0\1\131\3\0\1\55"+
    "\15\0\1\53\1\54\1\53\1\0\2\53\1\130\1\53"+
    "\1\217\16\53\2\0\12\53\4\0\1\55\1\0\1\131"+
    "\3\0\1\55\15\0\1\53\1\54\1\53\1\0\2\53"+
    "\1\130\10\53\1\220\7\53\2\0\12\53\4\0\1\55"+
    "\1\0\1\131\3\0\1\55\15\0\1\53\1\54\1\53"+
    "\1\0\2\53\1\130\1\53\1\221\16\53\2\0\12\53"+
    "\4\0\1\55\1\0\1\131\3\0\1\55\15\0\1\53"+
    "\1\54\1\53\1\0\2\53\1\130\20\53\2\0\3\53"+
    "\1\222\6\53\4\0\1\55\1\0\1\131\3\0\1\55"+
    "\15\0\1\53\1\54\1\53\1\0\2\53\1\130\2\53"+
    "\1\165\15\53\2\0\12\53\4\0\1\55\1\0\1\131"+
    "\3\0\1\55\15\0\1\53\1\54\1\53\1\0\2\53"+
    "\1\130\2\53\1\223\15\53\2\0\12\53\4\0\1\55"+
    "\1\0\1\131\3\0\1\55\15\0\1\53\1\54\1\53"+
    "\1\0\2\53\1\130\5\53\1\224\12\53\2\0\12\53"+
    "\4\0\1\55\1\0\1\131\3\0\1\55\15\0\1\53"+
    "\1\54\1\53\1\0\2\53\1\130\3\53\1\225\14\53"+
    "\2\0\12\53\4\0\1\55\1\0\1\131\3\0\1\55"+
    "\15\0\1\53\1\54\1\53\1\0\2\53\1\130\15\53"+
    "\1\220\2\53\2\0\12\53\4\0\1\55\1\0\1\131"+
    "\3\0\1\55\15\0\1\53\1\54\1\53\1\0\2\53"+
    "\1\130\2\53\1\226\15\53\2\0\12\53\4\0\1\55"+
    "\1\0\1\131\3\0\1\55\15\0\1\53\1\54\1\53"+
    "\1\0\2\53\1\130\10\53\1\227\7\53\2\0\12\53"+
    "\4\0\1\55\1\0\1\131\3\0\1\55\15\0\1\53"+
    "\1\54\1\53\1\0\2\53\1\130\13\53\1\220\4\53"+
    "\2\0\12\53\4\0\1\55\1\0\1\131\3\0\1\55"+
    "\15\0\1\53\1\54\1\53\1\0\2\53\1\130\20\53"+
    "\2\0\4\53\1\70\5\53\4\0\1\55\1\0\1\131"+
    "\3\0\1\55\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7080];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\1\1\1\11\21\1\3\11\1\1\5\11"+
    "\1\1\1\11\6\1\1\11\2\1\1\11\2\1\1\0"+
    "\34\1\1\0\3\11\1\0\7\11\1\0\1\11\2\0"+
    "\26\1\1\11\17\1\1\0\10\1\1\11\16\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
public String lexeme;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 214) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return DIVISION;
            }
          case 42: break;
          case 2: 
            { lexeme=yytext(); return ERROR;
            }
          case 43: break;
          case 3: 
            { return PARENTESISD;
            }
          case 44: break;
          case 4: 
            { /*Ignore*/
            }
          case 45: break;
          case 5: 
            { return DIRECTIVAS;
            }
          case 46: break;
          case 6: 
            { return MODULO;
            }
          case 47: break;
          case 7: 
            { return ANGLED;
            }
          case 48: break;
          case 8: 
            { return ANGLEI;
            }
          case 49: break;
          case 9: 
            { return PUNTO;
            }
          case 50: break;
          case 10: 
            { return COMA;
            }
          case 51: break;
          case 11: 
            { return PARENTESISI;
            }
          case 52: break;
          case 12: 
            { return INICIOB;
            }
          case 53: break;
          case 13: 
            { return FINALB;
            }
          case 54: break;
          case 14: 
            { return ASIGNACION;
            }
          case 55: break;
          case 15: 
            { return DOSP;
            }
          case 56: break;
          case 16: 
            { return SUMA;
            }
          case 57: break;
          case 17: 
            { return MULTIPLICACION;
            }
          case 58: break;
          case 18: 
            { return RESTA;
            }
          case 59: break;
          case 19: 
            { return ASPERSON;
            }
          case 60: break;
          case 20: 
            { return NOT;
            }
          case 61: break;
          case 21: 
            { return POW;
            }
          case 62: break;
          case 22: 
            { return COMILLAD;
            }
          case 63: break;
          case 23: 
            { return COMILLAS;
            }
          case 64: break;
          case 24: 
            { lexeme=yytext(); return VAR;
            }
          case 65: break;
          case 25: 
            { lexeme=yytext(); return INT;
            }
          case 66: break;
          case 26: 
            { lexeme=yytext(); return FLOAT;
            }
          case 67: break;
          case 27: 
            { lexeme=yytext(); return PR;
            }
          case 68: break;
          case 28: 
            { lexeme=yytext(); return HTML;
            }
          case 69: break;
          case 29: 
            { return COMPARACION;
            }
          case 70: break;
          case 30: 
            { return SUMAM;
            }
          case 71: break;
          case 31: 
            { return MULTIPLICACIONM;
            }
          case 72: break;
          case 32: 
            { lexeme=yytext(); return COMENTARIO;
            }
          case 73: break;
          case 33: 
            { return RESTAM;
            }
          case 74: break;
          case 34: 
            { return AND;
            }
          case 75: break;
          case 35: 
            { return DIFERENTE;
            }
          case 76: break;
          case 36: 
            { return DIVISIONM;
            }
          case 77: break;
          case 37: 
            { return OR;
            }
          case 78: break;
          case 38: 
            { lexeme=yytext(); return TEXTO;
            }
          case 79: break;
          case 39: 
            { lexeme=yytext(); return OPERA;
            }
          case 80: break;
          case 40: 
            { lexeme=yytext(); return FUNCION;
            }
          case 81: break;
          case 41: 
            { lexeme=yytext(); return LIB;
            }
          case 82: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
